import type { ArenaConfig } from '../utils/arenaPersistence';

/**
 * Hard-coded demo ArenaConfig loaded by the "★ Demo" button.
 * Mirrors the arena built by scripts/create-demo-arena.js.
 *
 * Note: arena-parented traps/portals live in the top-level traps[]/portals[]
 * arrays (not inside ArenaSave), matching the ArenaConfig schema.
 */
export const DEMO_ARENA_CONFIG: ArenaConfig = {
  baseConfig: {
    height: 30, sides: 8, color: 0xe8dcc0, surface: 'plain',
    customTileData: null, tileScale: 20,
  },
  arenaSeq: 2,
  pitSeq: 0,
  zoneSeq: 3,
  wallSeq: 7,
  bridgeSeq: 2,
  segmentSeq: 6,
  speedLineSeq: 4,
  obstacleSeq: 3,
  trapSeq: 4,
  portalSeq: 2,
  rotationSeq: 2,
  footings: [],
  footingSeq: 0,
  jumpLinks: [],
  jumpLinkSeq: 0,
  translations: [],
  translationSeq: 0,

  baseWalls: [],  // free-standing walls on the octagon base (none in this demo)
  speedLines: [], // zone-parented speed lines (none in this demo)

  // ════════════════════════════════════════════════════════════════════════
  // Arenas
  // ════════════════════════════════════════════════════════════════════════
  arenas: [
    // ── Arena 1: Moat Arena ────────────────────────────────────────────────
    {
      id: 'arena-1', name: 'Moat Arena',
      openingShape: 'circle', wallProfile: 'spiral',
      radiusX: 60, radiusZ: 60, depth: 22, sides: 6, starInner: 0.5,
      color: 0x1a3a5c, surface: 'plain', customTileData: null, tileScale: 20,
      baseMaterial: 'abs',
      posX: 0, posZ: 0, posY: 0, rotY: 0,
      isMoat: true,
      innerRadiusX: 25, innerRadiusZ: 25,
      innerOpeningShape: 'circle', innerSides: 6, innerStarInner: 0.5,
      innerWallProfile: 'parabolic', innerRimOffset: 20,
      stepApplyToAll: false, stepEdgeProfiles: [], stepArcDivisions: 4,
      stepCount: 3, stepStartDepth: 0, stepRiserProfile: 'parabolic',
      rampMode: 'none', rampAngle: 0, rampWidth: 0,
      spiralTurns: 1.5, spiralClockwise: true, spiralCount: 2,
      spiralLedgeWidth: 5, spiralLedgeHeight: 2, spiralRadiusFrac: 0.65,
      stepsColor: null, stepsSurface: null, stepsCustomTileData: null,
      spiralColor: 0x2266aa, spiralSurface: null, spiralCustomTileData: null,
      lightColor: 0x4488ff, lightIntensity: 1.2, lightPosY: 40, lightRange: 120,
      particlePreset: 'void_motes',
      presentStlb64: null, presentColor: 0xffffff,
      pits: [],
      zones: [
        {
          id: 'zone-1', name: 'Water Zone',
          openingShape: 'circle', parentZoneId: null,
          radiusX: 14, radiusZ: 14, depth: 8, sides: 6, starInner: 0.5,
          color: 0x1155aa, surface: 'plain', customTileData: null, tileScale: 20,
          fill: 'water', fillColor: null, fillOpacity: 0.85,
          seamGlowColor: 0x00aaff, seamGlowIntensity: 0.6,
          particlePreset: 'none',
          posR: 42, posAngle: 45, rotY: 0,
          isMoat: false, innerRadiusX: 8, innerRadiusZ: 8,
          innerOpeningShape: 'circle', innerSides: 6, innerStarInner: 0.5,
          innerWallProfile: 'parabolic', innerRimOffset: 0,
          pits: [], zones: [],
        },
        {
          id: 'zone-2', name: 'Void Zone',
          openingShape: 'circle', parentZoneId: null,
          radiusX: 12, radiusZ: 12, depth: 8, sides: 6, starInner: 0.5,
          color: 0x220044, surface: 'plain', customTileData: null, tileScale: 20,
          fill: 'void', fillColor: null, fillOpacity: 0.9,
          seamGlowColor: 0x8800ff, seamGlowIntensity: 0.8,
          particlePreset: 'void_motes',
          posR: 42, posAngle: 225, rotY: 0,
          isMoat: false, innerRadiusX: 6, innerRadiusZ: 6,
          innerOpeningShape: 'circle', innerSides: 6, innerStarInner: 0.5,
          innerWallProfile: 'parabolic', innerRimOffset: 0,
          pits: [], zones: [],
        },
      ],
      walls: [
        {
          id: 'wall-1', name: 'Wave Wall', parentId: 'arena-1', parentType: 'arena',
          fullPerimeter: true, arcStart: 0, arcEnd: 360,
          basePosX: 0, basePosZ: 0, baseRotY: 0, baseLength: 60,
          height: 20, tilt: -20, thickness: 2, isDestructible: false, hitPoints: 100,
          autoJoin: true, moatRing: 'outer', rotateOnArena: false, arenaRotateMode: 'continuous',
          arenaRotateSpeed: 30, arenaRotateStepDeg: 30, arenaRotateStepInterval: 1,
          arenaRotateOscAmp: 45, arenaRotateOscFreq: 0.5,
          hasGaps: false, gapWidth: 10, panelWidth: 20,
          topProfile: 'waves', topAmplitude: 4, topFrequency: 6,
          isDouble: false, peakHeight: 10, peakTilt: 20,
          holes: [],
          color: 0x2255aa, surface: 'plain', customTileData: null, tileScale: 20,
          emissiveColor: 0x00e5ff, emissiveIntensity: 0.4, opacity: 1,
          material: 'abs',
          presentStlb64: null, presentColor: 0xffffff,
        },
        {
          id: 'wall-2', name: 'Step Wall', parentId: 'arena-1', parentType: 'arena',
          fullPerimeter: false, arcStart: 0, arcEnd: 180,
          basePosX: 0, basePosZ: 0, baseRotY: 0, baseLength: 60,
          height: 30, tilt: -35, thickness: 2, isDestructible: false, hitPoints: 100,
          autoJoin: true, moatRing: 'outer', rotateOnArena: false, arenaRotateMode: 'continuous',
          arenaRotateSpeed: 30, arenaRotateStepDeg: 30, arenaRotateStepInterval: 1,
          arenaRotateOscAmp: 45, arenaRotateOscFreq: 0.5,
          hasGaps: false, gapWidth: 10, panelWidth: 20,
          topProfile: 'serrated', topAmplitude: 5, topFrequency: 8,
          isDouble: false, peakHeight: 10, peakTilt: 20,
          holes: [],
          color: 0x334466, surface: 'plain', customTileData: null, tileScale: 20,
          emissiveColor: 0x2244aa, emissiveIntensity: 0.2, opacity: 1,
          material: 'stone',
          presentStlb64: null, presentColor: 0xffffff,
        },
        {
          id: 'wall-3', name: 'Straight Wall', parentId: 'arena-1', parentType: 'arena',
          fullPerimeter: false, arcStart: 180, arcEnd: 360,
          basePosX: 0, basePosZ: 0, baseRotY: 0, baseLength: 60,
          height: 15, tilt: 10, thickness: 2, isDestructible: false, hitPoints: 100,
          autoJoin: true, moatRing: 'outer', rotateOnArena: false, arenaRotateMode: 'continuous',
          arenaRotateSpeed: 30, arenaRotateStepDeg: 30, arenaRotateStepInterval: 1,
          arenaRotateOscAmp: 45, arenaRotateOscFreq: 0.5,
          hasGaps: false, gapWidth: 10, panelWidth: 20,
          topProfile: 'flat', topAmplitude: 0, topFrequency: 4,
          isDouble: false, peakHeight: 10, peakTilt: 20,
          holes: [],
          color: 0x3a5050, surface: 'plain', customTileData: null, tileScale: 20,
          emissiveColor: 0x003333, emissiveIntensity: 0.1, opacity: 1,
          material: 'abs',
          presentStlb64: null, presentColor: 0xffffff,
        },
        {
          id: 'wall-4', name: 'Outward Lean', parentId: 'arena-1', parentType: 'arena',
          fullPerimeter: false, arcStart: 60, arcEnd: 120,
          basePosX: 0, basePosZ: 0, baseRotY: 0, baseLength: 60,
          height: 25, tilt: 25, thickness: 2, isDestructible: false, hitPoints: 100,
          autoJoin: true, moatRing: 'outer', rotateOnArena: false, arenaRotateMode: 'continuous',
          arenaRotateSpeed: 30, arenaRotateStepDeg: 30, arenaRotateStepInterval: 1,
          arenaRotateOscAmp: 45, arenaRotateOscFreq: 0.5,
          hasGaps: false, gapWidth: 10, panelWidth: 20,
          topProfile: 'triangles', topAmplitude: 4, topFrequency: 5,
          isDouble: false, peakHeight: 10, peakTilt: 20,
          holes: [],
          color: 0x663322, surface: 'plain', customTileData: null, tileScale: 20,
          emissiveColor: 0xff6b35, emissiveIntensity: 0.3, opacity: 1,
          material: 'rubber',
          presentStlb64: null, presentColor: 0xffffff,
        },
      ],
      speedLines: [
        {
          id: 'sl-1', name: 'Whirlpool',
          parentArenaId: 'arena-1', parentZoneId: null,
          startR: 42, startAngle: 45, startDir: 90,
          segments: [
            { id: 'sl-1-seg-1', length: 30, rotX: 0, rotY: 60, rotZ: 0, speedMult: 1.2, objRotX: 0, objRotY: 0, objRotZ: 0 },
            { id: 'sl-1-seg-2', length: 30, rotX: 0, rotY: 60, rotZ: 0, speedMult: 1.5, objRotX: 0, objRotY: 0, objRotZ: 0 },
            { id: 'sl-1-seg-3', length: 30, rotX: 0, rotY: 60, rotZ: 0, speedMult: 1.8, objRotX: 0, objRotY: 0, objRotZ: 0 },
            { id: 'sl-1-seg-4', length: 30, rotX: 0, rotY: 60, rotZ: 0, speedMult: 2.0, objRotX: 0, objRotY: 0, objRotZ: 0 },
            { id: 'sl-1-seg-5', length: 30, rotX: 0, rotY: 60, rotZ: 0, speedMult: 2.2, objRotX: 0, objRotY: 0, objRotZ: 0 },
            { id: 'sl-1-seg-6', length: 30, rotX: 0, rotY: 60, rotZ: 0, speedMult: 2.5, objRotX: 0, objRotY: 0, objRotZ: 0 },
          ],
          surfaceFollow: true,
          targetType: 'any', targetTag: '',
          activationMode: 'always',
          triggerEvent: '', endEvent: '', activeDuration: 1000,
          period: 2000, activeDuty: 0.5,
          activationRadius: 30, fadeIn: 200, fadeOut: 300,
          oscillate: false, oscAxis: 'path',
          oscAmplitude: 5, oscFrequency: 1, oscPhase: 0,
          width: 3, color: 0x0088ff, opacity: 0.85, glowColor: 0x00ccff,
          customTileData: null, tileScale: 20,
          presentStlb64: null, presentColor: 0xffffff,
          speedMultiplier: 2.5,
          entryCondition: 'always',
          direction: 'forward',
          exitBehavior: 'normal',
          launchForce: 1, specialMoveName: '',
          allowMidAirEntry: false, overridePhysics: false, swapPriority: 0,
          presetType: 'custom', presetParams: { radiusX: 50, radiusZ: 50, sides: 6, petals: 5, turns: 3, steps: 36, centerX: 0, centerZ: 0, rotationY: 0, heightDelta: 0, closeLoop: false, innerRadius: 20, pitchPerTurn: 0, loopGap: 0, radiusEasing: 'linear', arcFraction: 1, centerY: 0, startPosX: 0, startPosY: 0, startPosZ: 0, endPosX: 0, endPosY: 0, endPosZ: 0, sections: [], modulation: { type: 'none', waveform: 'sine', amplitude: 0, periodSteps: 8, modPhase: 0, pulseWidth: 0.5 } },
          speedRamp: { profile: 'constant', speedMin: 1.5, speedMax: 1.5, entrySteps: 0, exitSteps: 0 },
          surfaceOffset: 0.05, surfaceOrientObject: true, airNormalMode: 'lean_center', airNormalTiltDeg: 10,
          baseCondition: 'none', conditionPhase: 'any', ejectBehavior: 'toward_center',
          targetSelectionMode: 'at_entrance', conditionCheckIntervalMs: 100,
          statModifiers: { spinRateMult: 1, staminaMult: 1, attackMult: 1, defenseMult: 1, weightMult: 1, burstResistMult: 1, tiltAngleDeg: 0, tiltSpinSensitive: false, tiltApplyPhase: 'exit' as const },
        },
        {
          id: 'sl-2', name: 'Flower Pattern',
          parentArenaId: 'arena-1', parentZoneId: null,
          startR: 10, startAngle: 0, startDir: 30,
          segments: [
            { id: 'sl-2-seg-1', length: 20, rotX: 0, rotY: 0,   rotZ: 0, speedMult: 1.0, objRotX: 0, objRotY: 30, objRotZ: 0 },
            { id: 'sl-2-seg-2', length: 20, rotX: 0, rotY: -15,  rotZ: 0, speedMult: 1.2, objRotX: 0, objRotY: 30, objRotZ: 0 },
            { id: 'sl-2-seg-3', length: 20, rotX: 0, rotY: 30,   rotZ: 0, speedMult: 1.4, objRotX: 0, objRotY: 30, objRotZ: 0 },
            { id: 'sl-2-seg-4', length: 20, rotX: 0, rotY: -15,  rotZ: 0, speedMult: 1.6, objRotX: 0, objRotY: 30, objRotZ: 0 },
            { id: 'sl-2-seg-5', length: 15, rotX: 0, rotY: 30,   rotZ: 0, speedMult: 1.8, objRotX: 0, objRotY: 30, objRotZ: 0 },
          ],
          surfaceFollow: true,
          targetType: 'any', targetTag: '',
          activationMode: 'always',
          triggerEvent: '', endEvent: '', activeDuration: 1000,
          period: 2000, activeDuty: 0.5,
          activationRadius: 20, fadeIn: 200, fadeOut: 300,
          oscillate: true, oscAxis: 'lateral',
          oscAmplitude: 3, oscFrequency: 0.8, oscPhase: 0,
          width: 2, color: 0xff00aa, opacity: 0.75, glowColor: 0xff66cc,
          customTileData: null, tileScale: 20,
          presentStlb64: null, presentColor: 0xffffff,
          speedMultiplier: 1.8,
          entryCondition: 'always',
          direction: 'bidirectional',
          exitBehavior: 'normal',
          launchForce: 1, specialMoveName: '',
          allowMidAirEntry: false, overridePhysics: false, swapPriority: 0,
          presetType: 'custom', presetParams: { radiusX: 50, radiusZ: 50, sides: 6, petals: 5, turns: 3, steps: 36, centerX: 0, centerZ: 0, rotationY: 0, heightDelta: 0, closeLoop: false, innerRadius: 20, pitchPerTurn: 0, loopGap: 0, radiusEasing: 'linear', arcFraction: 1, centerY: 0, startPosX: 0, startPosY: 0, startPosZ: 0, endPosX: 0, endPosY: 0, endPosZ: 0, sections: [], modulation: { type: 'none', waveform: 'sine', amplitude: 0, periodSteps: 8, modPhase: 0, pulseWidth: 0.5 } },
          speedRamp: { profile: 'constant', speedMin: 1.5, speedMax: 1.5, entrySteps: 0, exitSteps: 0 },
          surfaceOffset: 0.05, surfaceOrientObject: true, airNormalMode: 'lean_center', airNormalTiltDeg: 10,
          baseCondition: 'none', conditionPhase: 'any', ejectBehavior: 'toward_center',
          targetSelectionMode: 'at_entrance', conditionCheckIntervalMs: 100,
          statModifiers: { spinRateMult: 1, staminaMult: 1, attackMult: 1, defenseMult: 1, weightMult: 1, burstResistMult: 1, tiltAngleDeg: 0, tiltSpinSensitive: false, tiltApplyPhase: 'exit' as const },
        },
        {
          id: 'sl-3', name: 'Wall Climb',
          parentArenaId: 'arena-1', parentZoneId: null,
          startR: 55, startAngle: 270, startDir: 180,
          segments: [
            { id: 'sl-3-seg-1', length: 20, rotX: -30, rotY: 0, rotZ: 0, speedMult: 1.5, objRotX: 0, objRotY: 0, objRotZ: 0 },
            { id: 'sl-3-seg-2', length: 20, rotX: -40, rotY: 0, rotZ: 0, speedMult: 2.0, objRotX: 0, objRotY: 0, objRotZ: 0 },
            { id: 'sl-3-seg-3', length: 15, rotX: -50, rotY: 0, rotZ: 0, speedMult: 2.5, objRotX: 0, objRotY: 0, objRotZ: 0 },
          ],
          surfaceFollow: false,
          targetType: 'any', targetTag: '',
          activationMode: 'always',
          triggerEvent: '', endEvent: '', activeDuration: 1000,
          period: 2000, activeDuty: 0.5,
          activationRadius: 15, fadeIn: 100, fadeOut: 200,
          oscillate: false, oscAxis: 'path',
          oscAmplitude: 3, oscFrequency: 1, oscPhase: 0,
          width: 2.5, color: 0xffaa00, opacity: 0.9, glowColor: 0xffcc44,
          customTileData: null, tileScale: 20,
          presentStlb64: null, presentColor: 0xffffff,
          speedMultiplier: 2.0,
          entryCondition: 'always',
          direction: 'forward',
          exitBehavior: 'launch',
          launchForce: 2.0, specialMoveName: '',
          allowMidAirEntry: true, overridePhysics: false, swapPriority: 0,
          presetType: 'custom', presetParams: { radiusX: 50, radiusZ: 50, sides: 6, petals: 5, turns: 3, steps: 36, centerX: 0, centerZ: 0, rotationY: 0, heightDelta: 0, closeLoop: false, innerRadius: 20, pitchPerTurn: 0, loopGap: 0, radiusEasing: 'linear', arcFraction: 1, centerY: 0, startPosX: 0, startPosY: 0, startPosZ: 0, endPosX: 0, endPosY: 0, endPosZ: 0, sections: [], modulation: { type: 'none', waveform: 'sine', amplitude: 0, periodSteps: 8, modPhase: 0, pulseWidth: 0.5 } },
          speedRamp: { profile: 'constant', speedMin: 1.5, speedMax: 1.5, entrySteps: 0, exitSteps: 0 },
          surfaceOffset: 0.05, surfaceOrientObject: true, airNormalMode: 'lean_center', airNormalTiltDeg: 10,
          baseCondition: 'none', conditionPhase: 'any', ejectBehavior: 'toward_center',
          targetSelectionMode: 'at_entrance', conditionCheckIntervalMs: 100,
          statModifiers: { spinRateMult: 1, staminaMult: 1, attackMult: 1, defenseMult: 1, weightMult: 1, burstResistMult: 1, tiltAngleDeg: 0, tiltSpinSensitive: false, tiltApplyPhase: 'exit' as const },
        },
      ],
    },

    // ── Arena 2: Tower Arena ──────────────────────────────────────────────
    {
      id: 'arena-2', name: 'Tower Arena',
      openingShape: 'circle', wallProfile: 'step',
      radiusX: 22, radiusZ: 22, depth: 12, sides: 6, starInner: 0.5,
      color: 0x2d4a7a, surface: 'plain', customTileData: null, tileScale: 20,
      baseMaterial: 'abs',
      posX: 0, posZ: 0, posY: 20, rotY: 0,
      isMoat: false,
      innerRadiusX: 10, innerRadiusZ: 10,
      innerOpeningShape: 'circle', innerSides: 6, innerStarInner: 0.5,
      innerWallProfile: 'parabolic', innerRimOffset: 0,
      stepApplyToAll: true, stepEdgeProfiles: [], stepArcDivisions: 4,
      stepCount: 3, stepStartDepth: 3, stepRiserProfile: 'straight',
      rampMode: 'none', rampAngle: 0, rampWidth: 0,
      spiralTurns: 1, spiralClockwise: true, spiralCount: 1,
      spiralLedgeWidth: 4, spiralLedgeHeight: 1.5, spiralRadiusFrac: 0.6,
      stepsColor: 0x3a5a8a, stepsSurface: null, stepsCustomTileData: null,
      spiralColor: null, spiralSurface: null, spiralCustomTileData: null,
      lightColor: 0xff4400, lightIntensity: 1.5, lightPosY: 55, lightRange: 80,
      particlePreset: 'embers',
      presentStlb64: null, presentColor: 0xffffff,
      pits: [],
      zones: [
        {
          id: 'zone-3', name: 'Lava Zone',
          openingShape: 'circle', parentZoneId: null,
          radiusX: 8, radiusZ: 8, depth: 6, sides: 6, starInner: 0.5,
          color: 0x882200, surface: 'lava_rock', customTileData: null, tileScale: 20,
          fill: 'lava', fillColor: null, fillOpacity: 0.95,
          seamGlowColor: 0xff4400, seamGlowIntensity: 0.9,
          particlePreset: 'embers',
          posR: 8, posAngle: 90, rotY: 0,
          isMoat: false, innerRadiusX: 4, innerRadiusZ: 4,
          innerOpeningShape: 'circle', innerSides: 6, innerStarInner: 0.5,
          innerWallProfile: 'parabolic', innerRimOffset: 0,
          pits: [], zones: [],
        },
      ],
      walls: [
        {
          id: 'wall-5', name: 'Inward -45°', parentId: 'arena-2', parentType: 'arena',
          fullPerimeter: true, arcStart: 0, arcEnd: 360,
          basePosX: 0, basePosZ: 0, baseRotY: 0, baseLength: 22,
          height: 20, tilt: -45, thickness: 2, isDestructible: false, hitPoints: 100,
          autoJoin: true, moatRing: 'outer', rotateOnArena: false, arenaRotateMode: 'continuous',
          arenaRotateSpeed: 30, arenaRotateStepDeg: 30, arenaRotateStepInterval: 1,
          arenaRotateOscAmp: 45, arenaRotateOscFreq: 0.5,
          hasGaps: false, gapWidth: 10, panelWidth: 20,
          topProfile: 'flat', topAmplitude: 0, topFrequency: 4,
          isDouble: false, peakHeight: 10, peakTilt: 20,
          holes: [],
          color: 0x1a3355, surface: 'metal', customTileData: null, tileScale: 20,
          emissiveColor: 0x3366ff, emissiveIntensity: 0.5, opacity: 1,
          material: 'metal',
          presentStlb64: null, presentColor: 0xffffff,
        },
        {
          id: 'wall-6', name: 'Double Wall', parentId: 'arena-2', parentType: 'arena',
          fullPerimeter: false, arcStart: 240, arcEnd: 360,
          basePosX: 0, basePosZ: 0, baseRotY: 0, baseLength: 22,
          height: 18, tilt: 0, thickness: 2, isDestructible: false, hitPoints: 100,
          autoJoin: true, moatRing: 'outer', rotateOnArena: false, arenaRotateMode: 'continuous',
          arenaRotateSpeed: 30, arenaRotateStepDeg: 30, arenaRotateStepInterval: 1,
          arenaRotateOscAmp: 45, arenaRotateOscFreq: 0.5,
          hasGaps: false, gapWidth: 10, panelWidth: 20,
          topProfile: 'flat', topAmplitude: 0, topFrequency: 4,
          isDouble: true, peakHeight: 12, peakTilt: 30,
          holes: [],
          color: 0x446688, surface: 'plain', customTileData: null, tileScale: 20,
          emissiveColor: 0x224466, emissiveIntensity: 0.2, opacity: 1,
          material: 'abs',
          presentStlb64: null, presentColor: 0xffffff,
        },
      ],
      speedLines: [
        {
          id: 'sl-4', name: 'Tower Ring',
          parentArenaId: 'arena-2', parentZoneId: null,
          startR: 18, startAngle: 0, startDir: 90,
          segments: [
            { id: 'sl-4-seg-1', length: 25, rotX: 0, rotY: 90, rotZ: 0, speedMult: 1.5, objRotX: 0, objRotY: 0, objRotZ: 0 },
            { id: 'sl-4-seg-2', length: 25, rotX: 0, rotY: 90, rotZ: 0, speedMult: 2.0, objRotX: 0, objRotY: 0, objRotZ: 0 },
            { id: 'sl-4-seg-3', length: 25, rotX: 0, rotY: 90, rotZ: 0, speedMult: 2.5, objRotX: 0, objRotY: 0, objRotZ: 0 },
            { id: 'sl-4-seg-4', length: 25, rotX: 0, rotY: 90, rotZ: 0, speedMult: 3.0, objRotX: 0, objRotY: 0, objRotZ: 0 },
          ],
          surfaceFollow: true,
          targetType: 'any', targetTag: '',
          activationMode: 'always',
          triggerEvent: '', endEvent: '', activeDuration: 1000,
          period: 2000, activeDuty: 0.5,
          activationRadius: 20, fadeIn: 150, fadeOut: 200,
          oscillate: false, oscAxis: 'path',
          oscAmplitude: 3, oscFrequency: 1, oscPhase: 0,
          width: 2, color: 0xff6600, opacity: 0.8, glowColor: 0xff9944,
          customTileData: null, tileScale: 20,
          presentStlb64: null, presentColor: 0xffffff,
          speedMultiplier: 3.0,
          entryCondition: 'always',
          direction: 'forward',
          exitBehavior: 'normal',
          launchForce: 1, specialMoveName: '',
          allowMidAirEntry: false, overridePhysics: false, swapPriority: 0,
          presetType: 'custom', presetParams: { radiusX: 50, radiusZ: 50, sides: 6, petals: 5, turns: 3, steps: 36, centerX: 0, centerZ: 0, rotationY: 0, heightDelta: 0, closeLoop: false, innerRadius: 20, pitchPerTurn: 0, loopGap: 0, radiusEasing: 'linear', arcFraction: 1, centerY: 0, startPosX: 0, startPosY: 0, startPosZ: 0, endPosX: 0, endPosY: 0, endPosZ: 0, sections: [], modulation: { type: 'none', waveform: 'sine', amplitude: 0, periodSteps: 8, modPhase: 0, pulseWidth: 0.5 } },
          speedRamp: { profile: 'constant', speedMin: 1.5, speedMax: 1.5, entrySteps: 0, exitSteps: 0 },
          surfaceOffset: 0.05, surfaceOrientObject: true, airNormalMode: 'lean_center', airNormalTiltDeg: 10,
          baseCondition: 'none', conditionPhase: 'any', ejectBehavior: 'toward_center',
          targetSelectionMode: 'at_entrance', conditionCheckIntervalMs: 100,
          statModifiers: { spinRateMult: 1, staminaMult: 1, attackMult: 1, defenseMult: 1, weightMult: 1, burstResistMult: 1, tiltAngleDeg: 0, tiltSpinSensitive: false, tiltApplyPhase: 'exit' as const },
        },
      ],
    },
  ],

  // ════════════════════════════════════════════════════════════════════════
  // Bridges
  // ════════════════════════════════════════════════════════════════════════
  bridges: [
    {
      id: 'bridge-1', name: 'Loop Bridge',
      startRef: { type: 'arena', id: 'arena-1', angle: 0, wallHeight: 0, freePosX: 0, freePosY: 0, freePosZ: 0, freeDirDeg: 0 },
      section: {
        width: 12, crossSection: 'flat', depth: 4,
        hasLeftWall: true, hasRightWall: false, sideWallHeight: 12,
        material: 'abs',
        color: 0xaabbcc, surface: 'metal', customTileData: null, tileScale: 20,
        emissiveColor: 0x445566, emissiveIntensity: 0.2, opacity: 1,
      },
      color: 0xaabbcc, surface: 'metal',
      presentStlb64: null, presentColor: 0xffffff,
      segments: [
        {
          id: 'seg-1', name: 'Straight', orderIndex: 0, type: 'straight',
          length: 80, rampAngle: 0,
          curveRadius: 40, curveAngle: 90, curveDirection: 'left', bankAngle: 0,
          cp1X: 0, cp1Y: 0, cp1Z: 0, cp2X: 0, cp2Y: 0, cp2Z: 0,
          endX: 80, endY: 0, endZ: 0,
          loopRadius: 25, loopOrientation: 'vertical', tiltAngle: 0, corkscrewLength: 60, corkscrewTurns: 1,
          color: null, surface: null,
        },
        {
          id: 'seg-2', name: 'Loop', orderIndex: 1, type: 'loop',
          length: 40, rampAngle: 0,
          curveRadius: 25, curveAngle: 360, curveDirection: 'left', bankAngle: 0,
          cp1X: 0, cp1Y: 0, cp1Z: 0, cp2X: 0, cp2Y: 0, cp2Z: 0,
          endX: 0, endY: 0, endZ: 0,
          loopRadius: 25, loopOrientation: 'vertical', tiltAngle: 0, corkscrewLength: 60, corkscrewTurns: 1,
          color: null, surface: null,
        },
        {
          id: 'seg-3', name: 'Curve', orderIndex: 2, type: 'curve',
          length: 40, rampAngle: 0,
          curveRadius: 40, curveAngle: 90, curveDirection: 'left', bankAngle: 10,
          cp1X: 0, cp1Y: 0, cp1Z: 0, cp2X: 0, cp2Y: 0, cp2Z: 0,
          endX: 0, endY: 0, endZ: 0,
          loopRadius: 25, loopOrientation: 'vertical', tiltAngle: 0, corkscrewLength: 60, corkscrewTurns: 1,
          color: null, surface: null,
        },
      ],
      walls: [
        {
          id: 'wall-7', name: 'Bridge Rail', parentId: 'bridge-1', parentType: 'bridge',
          fullPerimeter: false, arcStart: 0, arcEnd: 360,
          basePosX: 0, basePosZ: 0, baseRotY: 0, baseLength: 60,
          height: 12, tilt: -15, thickness: 2, isDestructible: false, hitPoints: 100,
          autoJoin: true, moatRing: 'outer', rotateOnArena: false, arenaRotateMode: 'continuous',
          arenaRotateSpeed: 30, arenaRotateStepDeg: 30, arenaRotateStepInterval: 1,
          arenaRotateOscAmp: 45, arenaRotateOscFreq: 0.5,
          hasGaps: false, gapWidth: 10, panelWidth: 20,
          topProfile: 'flat', topAmplitude: 0, topFrequency: 4,
          isDouble: false, peakHeight: 6, peakTilt: 15,
          holes: [],
          color: 0x8899aa, surface: 'plain', customTileData: null, tileScale: 20,
          emissiveColor: 0x334455, emissiveIntensity: 0.1, opacity: 1,
          material: 'abs',
          presentStlb64: null, presentColor: 0xffffff,
        },
      ],
    },
    {
      id: 'bridge-2', name: 'Hairpin Bridge',
      startRef: { type: 'freepoint', id: '', angle: 0, wallHeight: 0, freePosX: 0, freePosY: 30, freePosZ: -40, freeDirDeg: 90 },
      section: {
        width: 10, crossSection: 'u_channel', depth: 5,
        hasLeftWall: false, hasRightWall: false, sideWallHeight: 10,
        material: 'stone',
        color: 0xcc9944, surface: 'concrete', customTileData: null, tileScale: 20,
        emissiveColor: 0x554422, emissiveIntensity: 0.1, opacity: 1,
      },
      color: 0xcc9944, surface: 'concrete',
      presentStlb64: null, presentColor: 0xffffff,
      segments: [
        {
          id: 'seg-4', name: 'Ramp', orderIndex: 0, type: 'ramp',
          length: 60, rampAngle: 20,
          curveRadius: 30, curveAngle: 90, curveDirection: 'right', bankAngle: 0,
          cp1X: 0, cp1Y: 0, cp1Z: 0, cp2X: 0, cp2Y: 0, cp2Z: 0,
          endX: 60, endY: 16, endZ: 0,
          loopRadius: 20, loopOrientation: 'vertical', tiltAngle: 0, corkscrewLength: 50, corkscrewTurns: 1,
          color: null, surface: null,
        },
        {
          id: 'seg-5', name: 'Hairpin', orderIndex: 1, type: 'hairpin',
          length: 40, rampAngle: 0,
          curveRadius: 20, curveAngle: 180, curveDirection: 'right', bankAngle: 20,
          cp1X: 0, cp1Y: 0, cp1Z: 0, cp2X: 0, cp2Y: 0, cp2Z: 0,
          endX: 0, endY: 0, endZ: 0,
          loopRadius: 20, loopOrientation: 'vertical', tiltAngle: 0, corkscrewLength: 50, corkscrewTurns: 1,
          color: null, surface: null,
        },
        {
          id: 'seg-6', name: 'Chicane', orderIndex: 2, type: 'chicane',
          length: 30, rampAngle: 0,
          curveRadius: 15, curveAngle: 45, curveDirection: 'left', bankAngle: 0,
          cp1X: 0, cp1Y: 0, cp1Z: 0, cp2X: 0, cp2Y: 0, cp2Z: 0,
          endX: 0, endY: 0, endZ: 0,
          loopRadius: 20, loopOrientation: 'vertical', tiltAngle: 0, corkscrewLength: 50, corkscrewTurns: 1,
          color: null, surface: null,
        },
      ],
      walls: [],
    },
  ],

  // ════════════════════════════════════════════════════════════════════════
  // Obstacles
  // ════════════════════════════════════════════════════════════════════════
  obstacles: [
    {
      id: 'obstacle-1', name: 'Boat A',
      shape: 'sphere', theme: 'boat',
      dimX: 14, dimY: 14, dimZ: 14,
      posX: 40, posY: 38, posZ: 0,
      rotX: 0, rotY: 0, rotZ: 0,
      isFloating: true, isDestructible: false, hitPoints: 100,
      contactForceX: 30, contactForceY: 0, contactForceZ: 0,
      color: 0xff6b35, surface: 'plain', customTileData: null, tileScale: 20,
      emissiveColor: 0xff4400, emissiveIntensity: 0.5, opacity: 1,
      material: 'rubber', speedPathId: null,
      presentStlb64: null, presentColor: 0xffffff,
    },
    {
      id: 'obstacle-2', name: 'Boat B',
      shape: 'cylinder', theme: 'boat',
      dimX: 10, dimY: 10, dimZ: 10,
      posX: -40, posY: 38, posZ: 0,
      rotX: 0, rotY: 0, rotZ: 0,
      isFloating: true, isDestructible: false, hitPoints: 100,
      contactForceX: -30, contactForceY: 0, contactForceZ: 0,
      color: 0x00e5ff, surface: 'plain', customTileData: null, tileScale: 20,
      emissiveColor: 0x0088cc, emissiveIntensity: 0.5, opacity: 1,
      material: 'rubber', speedPathId: null,
      presentStlb64: null, presentColor: 0xffffff,
    },
    {
      id: 'obstacle-3', name: 'Pillar',
      shape: 'cuboid', theme: 'rock',
      dimX: 10, dimY: 50, dimZ: 10,
      posX: 70, posY: 30, posZ: 70,
      rotX: 0, rotY: 0, rotZ: 0,
      isFloating: false, isDestructible: false, hitPoints: 500,
      contactForceX: 0, contactForceY: 0, contactForceZ: 0,
      color: 0x667788, surface: 'concrete', customTileData: null, tileScale: 20,
      emissiveColor: 0x223344, emissiveIntensity: 0.1, opacity: 1,
      material: 'stone', speedPathId: null,
      presentStlb64: null, presentColor: 0xffffff,
    },
  ],

  // ════════════════════════════════════════════════════════════════════════
  // Traps (all top-level — arena-parented and base-parented)
  // ════════════════════════════════════════════════════════════════════════
  traps: [
    {
      id: 'trap-1', name: 'Launch Pad',
      parentId: 'arena-1', parentType: 'arena',
      shape: 'circle', variant: 'trampoline', effect: 'launch',
      dimX: 20, dimZ: 20, rotY: 0,
      posR: 36, posAngle: 135, basePosX: 0, basePosZ: 0,
      forceX: 0, forceY: 80, forceZ: 0,
      damageFactor: 1, healFactor: 1, freezeDuration: 2,
      buffSurface: null,
      pitShape: 'circle', pitRadiusX: 10, pitRadiusZ: 10, pitDepth: 5,
      pitSides: 6, pitStarInner: 0.5,
      isPeriodic: false, safeInterval: 2, unsafeInterval: 2,
      activationLimit: 0, speedPathId: null,
      durationTiers: [],
      baseMaterial: 'rubber',
      color: 0xffcc00, surface: 'plain', customTileData: null, tileScale: 20,
      emissiveColor: 0xffaa00, emissiveIntensity: 0.5,
      presentStlb64: null, presentColor: 0xffffff,
      walls: [],
    },
    {
      id: 'trap-2', name: 'Buff Zone',
      parentId: 'arena-1', parentType: 'arena',
      shape: 'rectangle', variant: 'buff', effect: 'buff_zone',
      dimX: 24, dimZ: 24, rotY: 0,
      posR: 46, posAngle: 315, basePosX: 0, basePosZ: 0,
      forceX: 0, forceY: 0, forceZ: 0,
      damageFactor: 1, healFactor: 1, freezeDuration: 2,
      buffSurface: 'sand',
      pitShape: 'circle', pitRadiusX: 10, pitRadiusZ: 10, pitDepth: 5,
      pitSides: 6, pitStarInner: 0.5,
      isPeriodic: false, safeInterval: 2, unsafeInterval: 2,
      activationLimit: 0, speedPathId: null,
      durationTiers: [],
      baseMaterial: 'abs',
      color: 0xcc8800, surface: 'sand', customTileData: null, tileScale: 20,
      emissiveColor: 0xaa6600, emissiveIntensity: 0.3,
      presentStlb64: null, presentColor: 0xffffff,
      walls: [],
    },
    {
      id: 'trap-3', name: 'Saw Trap',
      parentId: 'arena-2', parentType: 'arena',
      shape: 'circle', variant: 'saw', effect: 'damage',
      dimX: 16, dimZ: 16, rotY: 0,
      posR: 15, posAngle: 270, basePosX: 0, basePosZ: 0,
      forceX: 0, forceY: 0, forceZ: 0,
      damageFactor: 1.5, healFactor: 1, freezeDuration: 2,
      buffSurface: null,
      pitShape: 'circle', pitRadiusX: 8, pitRadiusZ: 8, pitDepth: 4,
      pitSides: 6, pitStarInner: 0.5,
      isPeriodic: true, safeInterval: 1.0, unsafeInterval: 1.5,
      activationLimit: 0, speedPathId: null,
      durationTiers: [],
      baseMaterial: 'metal',
      color: 0xcc2200, surface: 'metal', customTileData: null, tileScale: 20,
      emissiveColor: 0xff2200, emissiveIntensity: 0.6,
      presentStlb64: null, presentColor: 0xffffff,
      walls: [],
    },
    {
      id: 'trap-4', name: 'Base Trampoline',
      parentId: 'octagon-base', parentType: 'base',
      shape: 'rectangle', variant: 'trampoline', effect: 'launch',
      dimX: 20, dimZ: 20, rotY: 0,
      posR: 0, posAngle: 0, basePosX: 80, basePosZ: 0,
      forceX: 0, forceY: 100, forceZ: 0,
      damageFactor: 1, healFactor: 1, freezeDuration: 2,
      buffSurface: null,
      pitShape: 'circle', pitRadiusX: 10, pitRadiusZ: 10, pitDepth: 5,
      pitSides: 6, pitStarInner: 0.5,
      isPeriodic: false, safeInterval: 2, unsafeInterval: 2,
      activationLimit: 0, speedPathId: null,
      durationTiers: [],
      baseMaterial: 'rubber',
      color: 0xeecc44, surface: 'plain', customTileData: null, tileScale: 20,
      emissiveColor: 0xddaa00, emissiveIntensity: 0.4,
      presentStlb64: null, presentColor: 0xffffff,
      walls: [],
    },
  ],

  // ════════════════════════════════════════════════════════════════════════
  // Portals (all top-level)
  // ════════════════════════════════════════════════════════════════════════
  portals: [
    {
      id: 'portal-1', name: 'Portal A',
      parentId: 'arena-1', parentType: 'arena',
      shape: 'circle', dimX: 16, dimZ: 16, rotY: 0,
      posR: 35, posAngle: 200, basePosX: 0, basePosZ: 0,
      destType: 'portal',
      destPortalId: 'portal-2', destArenaId: null,
      destPosX: 0, destPosY: 0, destPosZ: 0,
      exitVelScale: 1, exitRotY: NaN, isBidirectional: true,
      color: 0x00e5ff, glowColor: 0x00aaff,
      surface: 'plain', customTileData: null, tileScale: 20,
      presentStlb64: null, presentColor: 0xffffff,
    },
    {
      id: 'portal-2', name: 'Portal B',
      parentId: 'octagon-base', parentType: 'base',
      shape: 'circle', dimX: 16, dimZ: 16, rotY: 0,
      posR: 0, posAngle: 0, basePosX: -80, basePosZ: 0,
      destType: 'portal',
      destPortalId: 'portal-1', destArenaId: null,
      destPosX: 0, destPosY: 0, destPosZ: 0,
      exitVelScale: 1, exitRotY: NaN, isBidirectional: true,
      color: 0xff6b35, glowColor: 0xff9944,
      surface: 'plain', customTileData: null, tileScale: 20,
      presentStlb64: null, presentColor: 0xffffff,
    },
  ],

  // ════════════════════════════════════════════════════════════════════════
  // Rotations
  // ════════════════════════════════════════════════════════════════════════
  rotations: [
    {
      id: 'rot-1', name: 'Orbit A',
      memberIds: ['obstacle-1'], memberTypes: ['obstacle'],
      pivotX: 0, pivotY: 35, pivotZ: 0,
      mode: 'continuous', speed: 25, direction: 1,
      oscAmplitude: 30, oscFrequency: 0.5, oscPhase: 0,
      enabled: true,
      snapRules: [],
    },
    {
      id: 'rot-2', name: 'Orbit B',
      memberIds: ['obstacle-2'], memberTypes: ['obstacle'],
      pivotX: 0, pivotY: 35, pivotZ: 0,
      mode: 'continuous', speed: 18, direction: -1,
      oscAmplitude: 30, oscFrequency: 0.5, oscPhase: 180,
      enabled: true,
      snapRules: [],
    },
  ],
};
